In [2]:
import numpy as np


In [4]:
np.set_printoptions(suppress = True)

**Scaler, Vector, Matrix and Tensor**

In [11]:
scaler = 5.0;
print(scaler)

print("-"*40)

vector = np.array([3,7,2])
print("Vector:")

print(vector)

print("Shape of vector",vector.shape)

print("-"*40)

matrix = np.array([
    [1,2,3],
    [4,5,6]
])

print(matrix)
print("Shape of Matrix:",matrix.shape)

5.0
----------------------------------------
Vector:
[3 7 2]
Shape of vector (3,)
----------------------------------------
[[1 2 3]
 [4 5 6]]
Shape of Matrix: (2, 3)


In [15]:
v1 = np.array([1,3,5])
v2 = np.array([4,2,6])

print("v1:",v1)
print("v2:",v2)
diff = v2 - v1
dot = np.dot(v1,v2)
print("Dot Product of the vectors v1 and v2:",dot)
print("Difference of the vectors v1 and v2:",diff)

v1: [1 3 5]
v2: [4 2 6]
Dot Product of the vectors v1 and v2: 40
Difference of the vectors v1 and v2: [ 3 -1  1]


**Eucledian Distance**

In [18]:
diff = v2 - v1
print("Difference of the vectors v1 and v2:",diff)

difference = np.linalg.norm(diff)
print(difference)

Difference of the vectors v1 and v2: [ 3 -1  1]
3.3166247903554


**Matrix Multiplication and Linear Model**

In [21]:
x= np.array(
    [[1.0,30.0],
     [2.0,50.0],
     [3.0,70.0]]
)

print("x:\n",x)
print(x.shape)

x:
 [[ 1. 30.]
 [ 2. 50.]
 [ 3. 70.]]
(3, 2)


In [24]:
w = np.array([
    [0.5],
     [0.1]
])

print("w:\n",w)
print(w.shape)

w:
 [[0.5]
 [0.1]]
(2, 1)


In [25]:
xw = x@w

print(xw)

[[3.5]
 [6. ]
 [8.5]]


**Connecting to a Sample Dataset**

In [26]:
data = np.array([
    [85,26.6,31,0],
    [183,23.3,32,1],
    [89,28.1,21,0],
    [137,43.1,33,1]
])

print("\n Full Data Matrix:\n",data)
print("Data Shape:",data.shape)


 Full Data Matrix:
 [[ 85.   26.6  31.    0. ]
 [183.   23.3  32.    1. ]
 [ 89.   28.1  21.    0. ]
 [137.   43.1  33.    1. ]]
Data Shape: (4, 4)


In [27]:
x_features = data[:, :-1]
y_target = data[:, -1]

print("\nFeature matrix X:\n",x_features)
print("\nX Shape:\n",x_features.shape)

print("\nTarget vector Y:\n",y_target)
print("\nY Shape:\n",y_target.shape)


Feature matrix X:
 [[ 85.   26.6  31. ]
 [183.   23.3  32. ]
 [ 89.   28.1  21. ]
 [137.   43.1  33. ]]

X Shape:
 (4, 3)

Target vector Y:
 [0. 1. 0. 1.]

Y Shape:
 (4,)


In [28]:
A = np.array([[2, 1],
              [1, 3]])

B = np.array([5, 6])

np.linalg.solve(A, B)

array([1.8, 1.4])