**Setup**

In [26]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import(
    accuracy_score,precision_score,recall_score,f1_score,roc_auc_score
)

**Load Dataset**

In [27]:
df = pd.read_csv("diabetes.csv")

In [28]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [29]:
X = df.drop(columns=["Outcome"])
y = df["Outcome"]

**k-Fold Setup**

In [30]:
kf = KFold(n_splits = 5, shuffle=True, random_state=42)

**Loop Through the Folds**

In [31]:
for fold,(train_idx, test_idx) in enumerate(kf.split(X), start = 1):
    print(fold)
    print(len(train_idx))
    print(len(test_idx))
    print(train_idx[:5])
    print(test_idx[:5])
    print("-" *100)

1
614
154
[0 1 3 4 5]
[ 2  7 10 23 30]
----------------------------------------------------------------------------------------------------
2
614
154
[0 1 2 3 4]
[ 6 11 15 18 24]
----------------------------------------------------------------------------------------------------
3
614
154
[1 2 3 4 5]
[ 0  9 12 17 19]
----------------------------------------------------------------------------------------------------
4
615
153
[0 1 2 4 6]
[ 3  5  8 16 26]
----------------------------------------------------------------------------------------------------
5
615
153
[0 2 3 5 6]
[ 1  4 13 14 20]
----------------------------------------------------------------------------------------------------


In [32]:
accuracy_list = []
precision_list = []
recall_list = []
f1_list = []
roc_auc_list = []

In [33]:
for fold,(train_idx, test_idx) in enumerate(kf.split(X), start= 1):

    #Split the Data
    X_train,X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train,y_test = y.iloc[train_idx], y.iloc[test_idx]

    #Scale the data
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    #Train the Model
    model = LogisticRegression()
    model.fit(X_train_scaled,y_train)

    #Make the predictions
    y_pred = model.predict(X_test_scaled)
    y_prob = model.predict_proba(X_test_scaled)

    #Metrics
    acc = accuracy_score(y_test,y_pred)
    prec = precision_score(y_test,y_pred)
    rec = recall_score(y_test,y_pred)
    f1 = f1_score(y_test,y_pred)
    auc = roc_auc_score(y_test,y_pred)

    #Store the metrics
    accuracy_list.append(acc)
    precision_list.append(prec)
    recall_list.append(rec)
    f1_list.append(f1)
    roc_auc_list.append(auc)

    #Print Fold Result
    print(f"Fold {fold}")
    print(f"  Accuracy:{acc:.3f}")
    print(f"  Precision:{prec:.3f}")
    print(f"  Recall:{rec:.3f}")
    print(f"  F1 Score:{f1:.3f}")
    print(f"  ROC - AUC Score:{auc:.3f}")


Fold 1
  Accuracy:0.753
  Precision:0.649
  Recall:0.673
  F1 Score:0.661
  ROC - AUC Score:0.735
Fold 2
  Accuracy:0.786
  Precision:0.659
  Recall:0.617
  F1 Score:0.637
  ROC - AUC Score:0.738
Fold 3
  Accuracy:0.753
  Precision:0.780
  Recall:0.525
  F1 Score:0.627
  ROC - AUC Score:0.714
Fold 4
  Accuracy:0.804
  Precision:0.758
  Recall:0.532
  F1 Score:0.625
  ROC - AUC Score:0.728
Fold 5
  Accuracy:0.745
  Precision:0.732
  Recall:0.517
  F1 Score:0.606
  ROC - AUC Score:0.701


In [37]:
acc = round(np.mean(accuracy_list)*100,2)
prec = round(np.mean(precision_list)*100,2)
rec = round(np.mean(recall_list)*100,2)
f1 = round(np.mean(f1_list)*100,2)
roc = round(np.mean(roc_auc_list)*100,2)

print(f"Average Accuracy Score:{acc}%")
print(f"Average Precision Score:{prec}%")
print(f"Average Recall Score:{rec}%")
print(f"Average F1 Score:{f1}%")
print(f"Average AUC-PUC Score:{roc}%")

Average Accuracy Score:76.82%
Average Precision Score:71.56%
Average Recall Score:57.27%
Average F1 Score:63.13%
Average AUC-PUC Score:72.33%
